### ISSUE TITLE
Got a false passing test on this lesson

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-curriculum/fewpjs-acting-on-events#11]
When I ran `learn`  on my solution, both tests passed because my `moveDodgerLeft` and `moveDodgerRight` functions were written correctly. Yet, when I ran `open index.html` and tested it in my browser, the dodger didn't actually move right because I had forgotten to add the `moveDodgerRight` case to my event listener. You may want to add that to the test suite.

**Comment by sgharms** [comment]
It's a good point. Working tests != working app.

Faking events would require the implementation to name the callback that the event listener has so that we can fake a call to it (i.e. `eventHandlingCallback({ key: KEYS.keyDown })`) or something similar. I'll put in a caveat to "play test" but I don't think writing automated tests is the right call here.
