### ISSUE TITLE
Use of var

### ISSUE THREAD

**Issue by Dwake5** [learn-co-curriculum/fewpjs-acting-on-events#4]
You've said to never use var, but only to know about it for the future handling of legacy code. And yet you have use it here multiple times.

**Comment by rrcobb** [comment]
I think the issue might be that the Readme is slightly too prescriptive in https://github.com/learn-co-curriculum/fewpjs-jsf-hoisting. Using `let` and `const` will let you simplify your mental model for variables, since where you write them is where they'll be defined. 

Banning `var` is a nice simplification for the sake of preventing surprises with scope, but you'll see `var` in lots of code examples (and lots of production JavaScript!). The fix for this may be to soften and clarify the language in the other lab - the `var` use in this reading is okay (though violates the recommendation of the earlier lab)

**Comment by sgharms** [comment]
@Dwake5 @rrcobb Per your input @rrcobb I've updated the "never" language in https://github.com/learn-co-curriculum/fewpjs-jsf-hoisting/commit/76133362b08990490a72d47f37a52da1902202f7 to be less strict. The reality is that `var` exists in the wild and we should be flexible when encountering it, but we should bias to `let` and `const` for safety. I think that's all that can be done here. 

I'm closing assuming there's nothing else outstanding. Please re-open if there's a concern.
